#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

# npm run lint
npx lint-staged
npm run nuxiTypeCheck

# Run tests once
npm run test:watchfalse

# Store the exit code of the npm test command
TEST_EXIT_CODE=$?

# If any command failed, prevent the commit
if [ $TEST_EXIT_CODE -ne 0 ]; then
  echo "Pre-commit checks failed. Please fix the issues before committing."
  exit 1
fi

# If all commands pass, allow the commit
exit 0
